In [2]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install pillow

WARNING: Cache entry deserialization failed, entry ignored
Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.4.6-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
Using cached numpy-2.4.6-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.3

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (2.4.6)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Collecting matplotlib
  Using cached matplotlib-3.10.9-cp314-cp314-macosx_11_0_arm64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.63.0-cp314-cp314-macosx_10_15_universal2.whl.metadata (118 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.23 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (26.2)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-12.2.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Using cached matplotlib-3.10.9-cp314-cp314-macosx_11_0_arm64.whl (8.2 MB)
Using cached contourpy-1.3.3-cp314-cp314-macosx_11_0_arm64.whl (273 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.63.0-cp314-cp314-macosx_10_15_universal2.whl (2.9 MB)
Using cached kiwisolver-1.5.0-cp314-cp314-macosx_11_0_arm64.whl (64 kB)
Using cached pillow-12.2.0-cp314-cp314-macosx_11_0_arm64.whl (4.7 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.10.9 pillow-12.2.0 pyparsing-3.3.2

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pillow in ./.venv/lib/python3.14/site-packages (12.2.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [3]:
import os
import pandas as pd
from PIL import Image

dataset_path = "RP_lemonleaf"

data = []

for folder in sorted(os.listdir(dataset_path)):
    folder_path = os.path.join(dataset_path, folder)

    if os.path.isdir(folder_path):
        image_count = 0
        sample_size = None

        for file in os.listdir(folder_path):
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                image_count += 1

                if sample_size is None:
                    img = Image.open(os.path.join(folder_path, file))
                    sample_size = img.size

        data.append([folder, image_count, sample_size])

df = pd.DataFrame(data, columns=["Class", "Number of Images", "Pixel Size"])
df

                                       Class  Number of Images  Pixel Size
0                                Anthracnose               609  (512, 512)
1                              Citrus_Canker               623  (512, 512)
2              Citrus_Greening_Huanglongbing               618  (512, 512)
3                           Citrus_Leaf_Curl               634  (512, 512)
4                           Citrus_Leafminer               650  (512, 512)
5                         Healthy Lemon Leaf               630  (512, 512)
6  Swallowtail Larval Herbivory (Deficiency)               630  (512, 512)

In [5]:
import os
import pandas as pd
from PIL import Image

dataset_path = "IEEE_lemonleaf/Original_Dataset"

data = []

for folder in sorted(os.listdir(dataset_path)):
    folder_path = os.path.join(dataset_path, folder)

    if os.path.isdir(folder_path):
        image_count = 0
        sample_size = None

        for file in os.listdir(folder_path):
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                image_count += 1

                if sample_size is None:
                    img = Image.open(os.path.join(folder_path, file))
                    sample_size = img.size

        data.append([folder, image_count, sample_size])

df = pd.DataFrame(data, columns=["Class", "Number of Images", "Pixel Size"])
df

              Class  Number of Images    Pixel Size
0       Anthracnose               100  (1000, 1000)
1  Bacterial Blight               100  (1000, 1000)
2     Citrus Canker               100  (1000, 1000)
3        Curl Virus               100  (1000, 1000)
4   Deficiency Leaf               100  (1000, 1000)
5          Dry Leaf               100  (1000, 1000)
6      Healthy Leaf               100  (1000, 1000)
7       Sooty Mould               100  (1000, 1000)
8      Spider Mites               100  (1000, 1000)

In [11]:
import os
from PIL import Image
import hashlib
dataset_path = "IEEE_lemonleaf/Original_Dataset"


corrupt_images = []
empty_files = []
hash_dict = {}
duplicates = []

# Function to get file hash (for duplicates)
def get_hash(file_path):
    with open(file_path, "rb") as f:
        return hashlib.md5(f.read()).hexdigest()

for class_name in os.listdir(dataset_path):
    class_path = os.path.join(dataset_path, class_name)

    if not os.path.isdir(class_path):
        continue

    for img_name in os.listdir(class_path):
        img_path = os.path.join(class_path, img_name)

   
        # 1. Check empty file
        if os.path.getsize(img_path) == 0:
            empty_files.append(img_path)
            continue

   
        # 2. Check corrupt image
        try:
            img = Image.open(img_path)
            img.verify()
        except:
            corrupt_images.append(img_path)
            continue


        # 3. Check duplicates
        try:
            file_hash = get_hash(img_path)

            if file_hash in hash_dict:
                duplicates.append((img_path, hash_dict[file_hash]))
            else:
                hash_dict[file_hash] = img_path
        except:
            pass


# RESULTS

print("\n========== DATASET REPORT ==========\n")

print(f"Corrupt images   : {len(corrupt_images)}")
print(f"Empty files      : {len(empty_files)}")
print(f"Duplicate images : {len(duplicates)}")

print("\n---------- SAMPLE ISSUES ----------\n")

print("Corrupt examples:")
for img in corrupt_images[:5]:
    print(img)
print("\nEmpty file examples:")
for img in empty_files[:5]:
    print(img)
print("\nDuplicate examples:")
for dup in duplicates[:5]:
    print(dup)


print("CHECK COMPLETED ✔")

========== DATASET REPORT ==========

Corrupt images   : 0
Empty files      : 0
Duplicate images : 0

---------- SAMPLE ISSUES ----------

Corrupt examples:

Empty file examples:

Duplicate examples:
CHECK COMPLETED ✔

In [12]:
import os
from PIL import Image
import hashlib
dataset_path = "RP_lemonleaf"


corrupt_images = []
empty_files = []
hash_dict = {}
duplicates = []

# Function to get file hash (for duplicates)
def get_hash(file_path):
    with open(file_path, "rb") as f:
        return hashlib.md5(f.read()).hexdigest()

for class_name in os.listdir(dataset_path):
    class_path = os.path.join(dataset_path, class_name)

    if not os.path.isdir(class_path):
        continue

    for img_name in os.listdir(class_path):
        img_path = os.path.join(class_path, img_name)

   
        # 1. Check empty file
        if os.path.getsize(img_path) == 0:
            empty_files.append(img_path)
            continue

   
        # 2. Check corrupt image
        try:
            img = Image.open(img_path)
            img.verify()
        except:
            corrupt_images.append(img_path)
            continue


        # 3. Check duplicates
        try:
            file_hash = get_hash(img_path)

            if file_hash in hash_dict:
                duplicates.append((img_path, hash_dict[file_hash]))
            else:
                hash_dict[file_hash] = img_path
        except:
            pass


# RESULTS

print("\n========== DATASET REPORT ==========\n")

print(f"Corrupt images   : {len(corrupt_images)}")
print(f"Empty files      : {len(empty_files)}")
print(f"Duplicate images : {len(duplicates)}")

print("\n---------- SAMPLE ISSUES ----------\n")

print("Corrupt examples:")
for img in corrupt_images[:5]:
    print(img)
print("\nEmpty file examples:")
for img in empty_files[:5]:
    print(img)
print("\nDuplicate examples:")
for dup in duplicates[:5]:
    print(dup)


print("CHECK COMPLETED ✔")

========== DATASET REPORT ==========

Corrupt images   : 0
Empty files      : 0
Duplicate images : 0

---------- SAMPLE ISSUES ----------

Corrupt examples:

Empty file examples:

Duplicate examples:
CHECK COMPLETED ✔